### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Gerryjj** [DavoudTaghawiNejad/abce#1]
probably finger trouble at my end as a newbie to Python & abce. I hope you can help...
i am using win 8.1.
The \doc reads a little differently to the readme..
the readme states:
copy abce/example to your_model_path::

1.    cd your_model_path
    cp ../abce/template/* .

2. In line 3 of `start.py`: adjust sys.path.append('your_path_to/abce/lib')
Not sure what you mean by your model path but you can see in the TREE command below what i inferred. 
 Regarding 2. i don't see "sys.path.append" in start.py.
You can see from the path command below how i have set up paths.

When i run start.py from the copied templates i get...
C:\Programs\abce-master\template>start.py
Traceback (most recent call last):
  File "C:\Programs\abce-master\template\start.py", line 2, in <module>
    from firm import Firm
  File "C:\Programs\abce-master\template\firm.py", line 2, in <module>
    import abce
ImportError: No module named abce

Please advise what steps or changes i am missing, thanks...
The path and tree commands follow.....

abce path
C:\Windows\System32>path
PATH=C:\Python27\Lib\site-packages;C:\Python27\Lib\site-packages\PyQt4;
C:\Programs\Pure\;C:\Programs\Pure\lib;C:\Program Files (x86)\Java\jdk1.7.0_65\bin;
C:\Python27;C:\Python27\DLLs;C:\Python27\Scripts;C:\Python27\gnuplot\binary;
C:\Program Files (x86)\pythonxy\SciTE-3.3.2-3;C:\Program Files (x86)\pythonxy\console;
C:\MinGW32-xy\bin;
C:\Programs\abce-master\abce\lib;
C:\Program Files (x86)\Vensim\Venple.exe;C:\Programs\Pure\;C:\Programs\EMAworkbench-master\src;C:\Programs\EMAworkbench-master\src\examples;C:\Programs\EMAworkbench-master\src\expWorkbench

abce-tree
C:\Windows\System32>tree c:\programs\abce-master /f
Folder PATH listing for volume Windows
Volume serial number is 0000000A EE6A:1709
C:\PROGRAMS\ABCE-MASTER
│   .gitignore
│   abce-master.zip
│   ABCE.pdf
│   MANIFEST.in
│   README.rst
│   setup.py
│
├───abce
│   │   abcelogger.py
│   │   agent.py
│   │   database.py
│   │   db.py
│   │   firm.py
│   │   firmmultitechnologies.py
│   │   from_gams.py
│   │   household.py
│   │   logger.py
│   │   messaging.py
│   │   postprocess.py
│   │   postprocess.R
│   │   subround.py
│   │   tools.py
│   │   trade.py
│   │   __init__.py
│   │
│   └───lib
│       └───template
│               agents_parameters.csv
│               config.py
│               firm.py
│               firm.pyc
│               household.py
│               script.R
│               simulation_parameters.csv
│               start.py
│
├───doc
│       abcetools.rst
│       Agent_class.rst
│       amazon_ec2.rst
│       conf.py
│       Database.rst
│       examples.rst
│       files.rst
│       Firm.rst
│       FirmMultiTechnologies.rst
│       Household.rst
│       index.rst
│       installation.rst
│       introduction.rst
│       make.bat
│       Makefile
│       messagemodel.jpg
│       Messaging.rst
│       parameters.rst
│       simulation.rst
│       simulation_results.rst
│       sphinxarticle.cls
│       Trade.rst
│       unit_testing.rst
│       Walk_through.rst
│
├───example
│   │   README.rst
│   │
│   ├───2sectors
│   │       agents_parameters.csv
│   │       config.py
│   │       firm.py
│   │       household.py
│   │       script.R
│   │       simulation_parameters.csv
│   │       start.py
│   │
│   └───one_household_one_firm
│           config.py
│           firm.py
│           household.py
│           script.R
│           simulation_parameters.csv
│           start.py
│
├───template
│       abce_templates-0.3.zip
│       agents_parameters.csv
│       config.py
│       firm.py
│       firm.pyc
│       household.py
│       script.R
│       simulation_parameters.csv
│       start.py
│
└───unittest
        agents_parameters.csv
        buy.py
        config.py
        endowment.py
        give.py
        logger.py
        nohup.out
        quote_buy.py
        sell.py
        simulation_parameters.csv
        start.py

**Comment by tswenzel** [comment]
Hi Davoud, 

I saw the installation instructions for Ubuntu and Windows. 

I suppose that means it does not run on Mac then, does it? 

Thanks & Regards, 
Tina

**Comment by tswenzel** [comment]
Adding to the above, installation on mac worked on the first attempt...Thanks, T

**Comment by DavoudTaghawiNejad** [comment]
Hello,

ABCE has been substantially rewritten and this issue is resolved. ABCE 0.5 is currently in an alpha release.
