### ISSUE TITLE
production.csv and buy.csv are empty

### ISSUE THREAD

**Issue by tswenzel** [DavoudTaghawiNejad/abce#3]
Hi Davoud, 

After installing, I ran the one_household_one_firm example which runs and produces the files in the results folder. Nevertheless, the production and buy csv files are empty. 

I tried re-installing, but the problem persists, and imported sqlite3 beforehand. 

Do you have any idea why this could occur ? 

Thanks & Regards, 
Tina

**Comment by DavoudTaghawiNejad** [comment]
Hi Tina,

could you please run the simulation in the /unittest directory and send the output to me? It runs a full test of all data recording routines.
There might be a bug in the newest version. If this is the case I will sort it out this week.

Davoud@Taghawi-Nejad.de

Davoud

**Comment by DavoudTaghawiNejad** [comment]
Hello Tina,

I just did an epic rewrite of ABCE. Its internal structure is simplified. The issue you described is resolved.

Davoud
